=== ribaban-DAW/LenguajeDeMarcas/EjerciciosXSD/Ejercicio4/eventos.dtd
<!ELEMENT eventos (evento)+>
<!ELEMENT evento (nombre, mes, lugar, duracion, organizador)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT organizador (nombre_o, profesion, fecha_nac, ciudad, telefono, email)>
<!ELEMENT nombre_o (#PCDATA)>
<!ELEMENT profesion (#PCDATA)>
<!ELEMENT fecha_nac (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ATTLIST ciudad cp CDATA #REQUIRED>
<!ELEMENT telefono EMPTY>
<!ATTLIST telefono n CDATA #REQUIRED>
<!ELEMENT email (#PCDATA)>

=== ribaban-DAW/LenguajeDeMarcas/EjerciciosXSD/Ejercicio4/eventos_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventos SYSTEM "eventos.dtd">
<eventos>
	<evento>
		<nombre>Diverciencia</nombre>
		<mes>Mayo</mes>
		<lugar>Algeciras</lugar>
		<duracion>1 semana</duracion>
		<organizador>
			<nombre_o>Juan Manuel C.</nombre_o>
			<profesion>Matemático</profesion>
			<fecha_nac>07/05/1960</fecha_nac>
			<ciudad cp="29700">Málaga</ciudad>
			<telefono n="666666666" />
			<email>lm@prueba.com</email>
		</organizador>
	</evento>
</eventos>
