=== ribaban-DAW/LenguajeDeMarcas/EjerciciosDTD/Ejercicio5/moviles.dtd
<!ELEMENT moviles (movil+)>
<!ELEMENT movil (modelo, precio, fabricante, color)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT fabricante (#PCDATA)>
<!ELEMENT color (#PCDATA)>

=== ribaban-DAW/LenguajeDeMarcas/EjerciciosDTD/Ejercicio5/moviles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE moviles SYSTEM "moviles.dtd">
<moviles>
	<movil>
		<modelo>ModElus</modelo>
		<precio>300</precio>
		<fabricante>Elfa Bricante</fabricante>
		<color>Morado</color>
	</movil>
	<movil>
		<modelo>ModHeladus</modelo>
		<precio>1200</precio>
		<fabricante>Unai Guana</fabricante>
		<color>Rosa</color>
	</movil>
</moviles>
